apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-upload-pvc
  namespace: bolx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
