apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bolxwmsdev
  template:
    metadata:
      labels:
        app: bolxwmsdev
    spec:
      containers:
      - name: bolxwms
        image: aravindaravind/fileupload-app:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/app/wwwroot/upload"
          name: file-upload-volume
      volumes:
      - name: file-upload-volume
        persistentVolumeClaim:
          claimName: file-upload-pvc
      imagePullSecrets:
      - name: dockerhub
