apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
  labels:
    app: bolxwmsdev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bolxwmsdev
  template:
    metadata:
      labels:
        app: bolxwmsdev
    spec:
      containers:
      - name: bolxwms
        image: aravindaravind/fileupload-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dockerhub

---

apiVersion: v1
kind: Service
metadata:
  name: upload-service
  labels:
    app: bolxwmsdev  
spec:
  selector:
    app: bolxwmsdev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 31003
  type: NodePort
