apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
  namespace: bolx
  labels:
    app: bolxwmsdev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bolxwmsdev
  template:
    metadata:
      labels:
        app: bolxwmsdev
    spec:
      initContainers:
      - name: init-file-upload
        image: busybox
        command: ['sh', '-c', 'cp -r /var/lib/jenkins/workspace/* /mnt/upload && cp -r /app/wwwroot/upload/* /mnt/upload']
        volumeMounts:
        - mountPath: /var/lib/jenkins/workspace
          name: jenkins-workspace-volume
        - mountPath: /app/wwwroot/upload
          name: file-upload-volume
        - mountPath: /mnt/upload
          name: jenkins-workspace-volume  # Use the same volume for both mounts
      containers:
      - name: bolxwms
        image: aravindaravind/fileupload-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /app/wwwroot/upload
          name: file-upload-volume
      volumes:
      - name: file-upload-volume
        persistentVolumeClaim:
          claimName: file-upload-pvc
      - name: jenkins-workspace-volume
        hostPath:
          path: /var/lib/jenkins/workspace/kube/FileUpload/wwwroot/upload/
      imagePullSecrets:
      - name: dockerhub
