apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
  namespace: bolx
  labels:
    app: bolxwmsdev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bolxwmsdev
  template:
    metadata:
      labels:
        app: bolxwmsdev
    spec:
      initContainers:
      - name: init-file-upload
        image: busybox
        command: ['sh', '-c', 'cp -r /app/wwwroot/upload/* /mnt/upload']
        volumeMounts:
        - mountPath: /mnt/upload
          name: persistent-upload-volume
        - mountPath: /app/wwwroot/upload
          name: app-upload-volume
      - name: copy-back-files
        image: busybox
        command: ['sh', '-c', 'cp -r /mnt/upload/* /app/wwwroot/upload/']
        volumeMounts:
        - mountPath: /mnt/upload
          name: persistent-upload-volume
        - mountPath: /app/wwwroot/upload
          name: app-upload-volume
      containers:
      - name: bolxwms
        image: aravindaravind/fileupload-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app/wwwroot/upload
          name: app-upload-volume
      volumes:
      - name: persistent-upload-volume
        persistentVolumeClaim:
          claimName: file-upload-pvc
      - name: app-upload-volume
        emptyDir: {}
      imagePullSecrets:
      - name: dockerhub
