apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
  namespace: bolx
  labels:
    app: bolxwmsdev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bolxwmsdev
  template:
    metadata:
      labels:
        app: bolxwmsdev
    spec:
      containers:
      - name: bolxwms
        image: aravindaravind/fileupload-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app/wwwroot/upload
          name: file-upload-volume
      - name: file-upload-sidecar
        image: alpine:latest  # Use alpine as a placeholder
        command: ['sh', '-c', 'while true; do rsync -au /mnt/upload/ /app/wwwroot/upload; sleep 30; done']  # Use rsync for efficiency
        volumeMounts:
        - mountPath: /mnt/upload
          name: file-upload-volume
        - mountPath: /app/wwwroot/upload
          name: file-upload-volume
      volumes:
      - name: file-upload-volume
        persistentVolumeClaim:
          claimName: file-upload-pvc
      imagePullSecrets:
      - name: dockerhub
